### ISSUE TITLE
Will forcehybrid get a dev preview release also?

### ISSUE THREAD

**Issue by dfattlar** [forcedotcom/SalesforceMobileSDK-Package#124]
I saw that `forceios` had the dev preview uploaded to NPM here: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2614

Will `forcehybrid` also be getting a dev preview release to fix for Xcode 10 / iOS12? 
If not, will it be enough to install the SDK pointing at the dev branch (without using upgrade path via `forcehybrid`)?

**Comment by wmathurin** [comment]
There is no plans for a 7.0.0.preview for forcehybrid.
But 7.0 scheduled for Nov/Dec will be for all the force* tools.

**Comment by pbergner** [comment]
@wmathurin so we just won't be able to build with xcode10/ios12 for a month or two? Do you have a workaround?

**Comment by wmathurin** [comment]
@pbergner Build using Xcode 9, the app will work on ios 12 devices.

**Comment by pbergner** [comment]
@wmathurin it does not that's the problem. I downloaded Xcode 9.4.1 and attempting to build to an iOS12 device results in the following error:

[https://imgur.com/a/CSYGwVs](url)

The only workaround is to build the .ipa file and install it manually through iTunes. This process isn't practical for actual development.

**Comment by wmathurin** [comment]
I understand: don't target ios12, build for ios11, the app will work fine on iOS 12 devices.

**Comment by pbergner** [comment]
@wmathurin are you referring to iOS Deployment Target? If so, mine is set to iOS 10.0. Or are you referring to something else?
