### ISSUE TITLE
SQLite Issue

### ISSUE THREAD

**Issue by sarathi0333** [forcedotcom/SalesforceMobileSDK-Package#196]
I created a Sample app using Forcehybrid CLI. As per the documentation [https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/reference_current_versions.htm?search_text=sqlite](url)

Sqlite plugin, will it be installed by default by the mobile SDK? If so, i cannot see the plugin in the CLI created project.

I tried to install plugin manually, but ended up in the error `Must not define both SQLITE_OMIT_DECLTYPE and SQLITE_ENABLE_COLUMN_METADATA`

Issue raised in github [https://github.com/xpbrew/cordova-sqlite-storage/issues/906#issue-549481346](url)

Please suggest.

**Comment by wmathurin** [comment]
We don't use the SQLite plugin.

Instead, for storage, we have SmartStore which internally uses SQLCipher (a secure version of SQLite).

For more information see:
https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/offline_intro.htm
https://www.zetetic.net/sqlcipher/
