### ISSUE TITLE
xcode build issue

### ISSUE THREAD

**Issue by kai-wang** [forcedotcom/SalesforceMobileSDK-Package#212]
Hi there,

I got this issue when building in xcode.

**Double-quoted include "YGMacros.h" in framework header, expected angle-bracketed instead**

Changing to <YGMachros.h> doesn't work.

My xcode version is Version 11.3.1 (11C505)
 cocoapod version is 1.8.0

**Comment by kai-wang** [comment]
I move this to the reactnative repo

**Comment by wmathurin** [comment]
We need more info. How did you generate your application? What version of Mobile SDK are you using?

**Comment by kai-wang** [comment]
I just generate the application by following instructions.

1. forcereact create
Enter the target platform(s) separated by commas (ios, android): ios
Enter your application name: FirstReact
Enter your package name: com.bestapps.ios
Enter your organization name (Acme, Inc.): BestApps.com
Enter output directory for your app (leave empty for the current directory): FirstReact

2. In Xcode, open FirstReact/ios/FirstReact.xcworkspace. and then try to build and run and got the above issue.

The force react version is 

forcereact version 8.3.0

I was wondering that was header search path issue and added $(SRCROOT)/../node_modules/react-native/ReactCommon as well, but didn't work.

![image](https://user-images.githubusercontent.com/2351552/95634337-642e4d80-0ad5-11eb-90d5-c71fa0367858.png)

**Comment by jbachand** [comment]
@kai-wang I had the same issue and the pre-released version of cocoapods fixes this. I'm not sure what caused it to break on older xcode versions.

Just run this before doing the next pod install and it clears it up:
`gem install cocoapods --pre`

Also see for reference: https://stackoverflow.com/questions/63951540/googledatatransport-is-throwing-double-quoted-include-in-framework-header-expect

**Comment by kai-wang** [comment]
Thanks Jeff, that solved the problem
