### ISSUE TITLE
Event for Back button in Login page

### ISSUE THREAD

**Issue by rsiuli001** [forcedotcom/SalesforceMobileSDK-Package#213]
![85673604-afb51b00-b6e1-11ea-921f-b3bc1cea680b](https://user-images.githubusercontent.com/62182948/96116286-dce23f00-0f05-11eb-9414-09272deba546.png)

Is there any way to track the event for the highlighted button in the login page?

**Comment by wmathurin** [comment]
You can customize the iOS login screen programmatically. See https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/oauth_hide_gear_icon.htm

(Also the issue should have been posted on the https://github.com/forcedotcom/SalesforceMobileSDK-iOS repo).
