### ISSUE TITLE
mobilesync.cleanResyncGhosts() in React Native

### ISSUE THREAD

**Issue by rsiuli001** [forcedotcom/SalesforceMobileSDK-Package#214]
Hi Team,

I am currently using SDK 8.2 react-native and i want to clean the ghosts records from the local soup. I have gone through the following documentations but its throwing an error.

https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/entity_framework_sync_ghosts.htm

https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/entity_framework_native_inc_sync.htm?search_text=sync%20id

In the cleanResyncGhosts() method, we need to pass the sync_id in react native, is there any way we can get the sync Id based on the sync name?

Is there any template project with cleanResyncGhosts() in react-native?

Thanks

**Comment by wmathurin** [comment]
Use `getSyncStatus({"syncName": "xxx"})` to get all the details about a sync (including its id).

Our [mobile sync template for react native](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/tree/dev/MobileSyncExplorerReactNative) does not demonstrate clearResyncGhosts at this point.

**Comment by rsiuli001** [comment]
Hi @wmathurin I'm getting the following response from getSyncStatus().

I'm not getting sync_id in the sync status. Can you help me with this?

{
  "endTime": 1602823908226,
  "error": "",
  "maxTimeStamp": 1602514067000,
  "name": "leadSyncDown",
  "options": {
    "mergeMode": "OVERWRITE"
  },
  "progress": 100,
  "soupName": "lead",
  "startTime": 1602823907176,
  "status": "DONE",
  "target": {
    "query": "select Id,Name,Company,Status,Phone,MobilePhone,Em…' AND CountryCode ='US' order by LastModifiedDate",
    "modificationDateFieldName": "LastModifiedDate",
    "type": "soql",
    "iOSImpl": "SFSoqlSyncDownTarget",
    "idFieldName": "Id"
  },
  "totalSize": 0,
  "type": "syncDown",
  "_soupEntryId": 3
}

**Comment by wmathurin** [comment]
The sync id is 

> "_soupEntryId": 3
