### ISSUE TITLE
Unable to view smartstore inspector for mobile

### ISSUE THREAD

**Issue by pwketankulkarni** [forcedotcom/SalesforceMobileSDK-Package#219]
I have created app through forcereact command. To debug the smartstore I am trying to use smartstore inspector. As per documentation it is enabled by default but I am not able to see the option in Dev Support dialog box.
I have added following line of code in android/app/src/main/java/com/testApp/test/smartstore830/MainApplication.java
`SalesforceReactSDKManager.getInstance().setDevSupportEnabled(true);
`
following is the link for the documentation 
https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/tools_dev_support.htm

Version Information
"react-native": "0.63.2",
"react-native-force": "git+https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative.git#v8.3.0",

**Comment by wmathurin** [comment]
After generating the application with forcereact, you should be able to bring up the dev menu without any code changes when running the application from android studio (because it builds the debug version of the app) and it should show the smartstore inspector.

How are you running your application / did you change the build variant?

**Comment by pwketankulkarni** [comment]
@wmathurin thanks for the reply. I have not changed the build version, and I am running my application through terminal "react-native run-android".
I tried to run the app from android studio but still don't see the option

**Comment by wmathurin** [comment]
@pwketankulkarni  https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/216 looks similar to your issue and provides a workaround. Could you give it a try?

**Comment by wmathurin** [comment]
Closing as duplicate - please open a new issue (preferably against the SalesforceMobileSDK-ReactNative repo) if you feel your situation is different.
