### ISSUE TITLE
Latest cordova-android for hybrid app

### ISSUE THREAD

**Issue by akshayajeevan** [forcedotcom/SalesforceMobileSDK-Package#227]
Hi,

When I create a new hybrid android app using `forcehybrid` cli, I see it is creating the project with `cordova-android` of version 8.1.0. But in this repo it is updated to 9.0.0 ([constant.js](https://github.com/forcedotcom/SalesforceMobileSDK-Package/blob/4a2fce805fc362efa630202f6e945f9eb2abd0b8/shared/constants.js#L64)) 

Is it because npm is not updated with latest package ? If yes, can you please update the npm package ?

**Comment by wmathurin** [comment]
Your link points to a commit currently in the dev branch which has the code for the next release.

If you look at the file on the master branch (https://github.com/forcedotcom/SalesforceMobileSDK-Package/blob/master/shared/constants.js#L60) or under the 8.3.0 tag (https://github.com/forcedotcom/SalesforceMobileSDK-Package/blob/v8.3.0/shared/constants.js#L60), it will show the expected version.

**Comment by akshayajeevan** [comment]
My bad. Thanks @wmathurin

Any planned date for the upcoming release ?

**Comment by wmathurin** [comment]
Early feb #safeharbor
