### ISSUE TITLE
`create` fails within directory with spaces

### ISSUE THREAD

**Issue by JimmyBoh** [forcedotcom/SalesforceMobileSDK-Package#25]
**Platform:** Windows 10
**forcedroid Version:** 5.0.0

Problem:
Run `forcedroid create` from within a folder with a space in the name (`C:\Projects\My App\`). Git fails to clone due to the `path` arguments not being wrapped in quotes. The folder with spaces could occur at any level, not just the current directory.

**Comment by JimmyBoh** [comment]
Looks like [a simple change here.](https://github.com/forcedotcom/SalesforceMobileSDK-Package/blob/01fc9d0bda96509f5b0a4069dbe86cbd83ccac93/shared/utils.js#L286)

**Comment by trooper2013** [comment]
@JimmyBoh Thanks for reporting it. We will take a look

**Comment by bhariharan** [comment]
Fixed [here] (https://github.com/forcedotcom/SalesforceMobileSDK-Package/pull/27).

**Comment by JimmyBoh** [comment]
Thank you very much!
