### ISSUE TITLE
When Call  oauth.logout() there is a error 

### ISSUE THREAD

**Issue by NewTech2000** [forcedotcom/SalesforceMobileSDK-Package#258]
![1](https://user-images.githubusercontent.com/47728873/179998235-70d5a258-c735-43c1-a731-d25f6760437a.jpg)

**Comment by wmathurin** [comment]
Could you give us some details:
- mobile sdk version
- application type (what template was it generated from)
- android version

**Comment by wmathurin** [comment]
Closing for lack of details.
