### ISSUE TITLE
forcereact differed login app restarts automatically after login authentication is done .

### ISSUE THREAD

**Issue by iamRAJASHEKAR** [forcedotcom/SalesforceMobileSDK-Package#259]
Below are the steps followed to create projecct.
Link which i used for react native differed login https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/react_native_new_project.htm?q=defer .
Steps i followed to create project
1.Created project with **forcereact createWithTemplate**
2.I had given template as **ReactNativeDeferredTemplate**
3.After successful project creation switched to IOS folder and opened in Xcode ,and started metro bundler and ran IOS app .
4.Changed url in info.plist with our URL.
5.After successful launch on simulator i clicked on login and provided details to login ,on click of allow permission app restarted completely .
we are facing this issue as restarting whole app is uncertain and causing disturbed flow , nothing changes in the code default template itself behaves this way .

**Comment by wmathurin** [comment]
Unfortunately, that is the current behavior of the provided template.
