### ISSUE TITLE
Migrating react native version from 0.67.1 (default) to 0.70 

### ISSUE THREAD

**Issue by ManishPrakharan-Alstom** [forcedotcom/SalesforceMobileSDK-Package#267]
I am working on the react native project based on top of salesforce mobile SDK. When I create a project with the command
**forcereact createwithtemplate --templaterepouri=ReactNativeTemplate**  
I get the RN 0.67.1 version but the current RN version is 0.70.
Will there be any impact if i upgrade RN version to 0.70 ?

**Comment by wmathurin** [comment]
We should be release Mobile SDK 10.2 later this week which uses the latest React Native (0.70.1). Stay tuned. Thanks.
