### ISSUE TITLE
Error installing SalesforceApp-Android-238.050.0#3-s1-externalDev.apk

### ISSUE THREAD

**Issue by proudchild** [forcedotcom/SalesforceMobileSDK-Package#271]
Hello all,
i have followed the following trailhead: 
https://trailhead.salesforce.com/content/learn/projects/set-up-your-salesforce-mobile-developer-tools-for-lightning-web-components/install-salesforce-mobile-app-emulator-for-android
Downloaded the apk for testing from: 
https://developer.salesforce.com/tools/mobile-debugging?_ga=2.259854090.1666245179.1665763751-871882735.1663566154#

Im currently using Mac pro M1 as follows:

![Screen Shot 2022-10-14 at 13 18 47](https://user-images.githubusercontent.com/3269176/195893912-c4e75add-d70a-4e8b-a7a8-0647c07d8508.png)

And when i try to install the app the emulator throws an error.

<img width="436" alt="Screen Shot 2022-10-14 at 13 19 14" src="https://user-images.githubusercontent.com/3269176/195893986-560abe3c-2e8f-427b-9cd3-f334bf5ad4cd.png">

It would be nice to provide an salesforce app compatible with M1 Development Enviroment

**Comment by wmathurin** [comment]
This is not the right forum for this issue.
Maybe you can post your question on https://trailhead.salesforce.com/trailblazer-community/groups?tab=featured ?
