### ISSUE TITLE
ForceHybrid Create Issue With the Current Salesforce CLI

### ISSUE THREAD

**Issue by rvkntraja** [forcedotcom/SalesforceMobileSDK-Package#278]
The issue is with this SFDX CLI update: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm

The Git Project needs an update the Constants file to match the correct version of the SFDX CLI
From v6 to v2

Thanks
![image (1)](https://github.com/forcedotcom/SalesforceMobileSDK-Package/assets/41058666/2ec3f48a-ec38-4508-be1f-a3e6bcb47ae3)

**Comment by wmathurin** [comment]
forcehybrid still depends on sfdx. Could you install sfdx instead of sf?
We will switch to using sf in our next release.

**Comment by akshayajeevan** [comment]
@wmathurin - When are you planning to replace `sfdx` with `sf `for `forcehybrid `?
We have updated the cli to `sf `and not able to upgrade our `forcehybrid `app.

**Comment by wmathurin** [comment]
Probably in 12.0 (early next year). #safeharbor

**Comment by akshayajeevan** [comment]
@wmathurin - I uninstall `@salesforce/cli` and installed `sfdx-cli`. But still I am getting below error for `forcehybrid `-
```
Missing tools

toolName is not defined
```
Also I tried uninstalling and installing `forcehybrid `after `sfdx-cli`
Currently `sfdx version` command shows `sfdx-cli/7.209.6 win32-x64 node-v16.14.0`

Please help.

**Comment by wmathurin** [comment]
What happens if you do run `sfdx --version` from the command line?

**Comment by akshayajeevan** [comment]
@wmathurin 
Here is the output of `sfdx --version` and `forcehybrid`
```
>sfdx --version
sfdx-cli/7.209.6 win32-x64 node-v16.14.0

>forcehybrid
Missing tools

toolName is not defined
```

**Comment by brandonpage** [comment]
Hi @akshayajeevan, the only way I was able to reproduce the error you describe is with the new sf cli installed. You can try to run the following command to ensure that the old sfdx-cli is installed globally: `sudo npm i -g sfdx-cli --force`.

**Comment by akshayajeevan** [comment]
On my system installed cordova version is lower than the min version required. So this [line](https://github.com/forcedotcom/SalesforceMobileSDK-Package/blob/b29ad773e91cf10f81cecad477614a1164a47d21/shared/utils.js#L101) in the if block is causing the error. 
The `toolName `and `toolVersion` variables are not defined.

After updating the cordova version now its working.

**Comment by wmathurin** [comment]
Getting fixed with https://github.com/forcedotcom/SalesforceMobileSDK-Package/pull/283
