### ISSUE TITLE
Cocoapods pre-req could be more clear

### ISSUE THREAD

**Issue by BobDickinson** [forcedotcom/SalesforceMobileSDK-Package#35]
I'm new to this tool.  After following the directions in the Trailhead "Getting Started with Hybrid Development" unit, I ran forceios and got an error say that "pod" was not installed.  There was nothing in the tutorial about that pre-req, and being that I'd been using npm to install all of these tools, I naively did "sudo npm install -g pod", which installed the npm package "pod", which has nothing to do with Cocoapods or the "pod" that forceios was expecting.  I went down about a 60 minute rathole to figure that out and correct it.  

My suggestion would be that if you fail on "pod", you might give an error message explaining that Cocoapods is required.

It's also a little annoying that this pre-req is checked *after* you collect all of the app info interactively.

**Comment by rwhitley** [comment]
Thanks for catching our oversight in the trail. I'm fixing it now.

**Comment by bhariharan** [comment]
Thanks for your feedback @BobDickinson. We will incorporate this.
