### ISSUE TITLE
forceios create fails on Creating native app

### ISSUE THREAD

**Issue by davidfekke** [forcedotcom/SalesforceMobileSDK-Package#41]
I just upgraded to NPM 5, so I do not know if this is the cause, but I am getting the following error when I try to use this tool to create a native template.

Analyzing dependencies
Fetching podspec for `SalesforceAnalytics` from `node_modules/SalesforceMobileSDK-iOS`
[!] No podspec found for `SalesforceAnalytics` in `node_modules/SalesforceMobileSDK-iOS`
/Users/davidfekke/Documents/xcode
forceios create failed

Command failed: pod update

**Comment by davidfekke** [comment]
I reinstalled forceios, and now I am getting the following failure;

`
~/Documents/xcode  forceios create
Enter your application type (native, native_swift, react_native, hybrid_local, hybrid_remote): native
Enter your application name: SFNative
Enter the package name for your app (com.mycompany.myapp): com.swyftmobile.forsf
Enter your organization name (Acme, Inc.): Swyft Technology L.L.C.
Enter output directory for your app (leave empty for the current directory): SFNative

********************************************************************************
*
*   Creating ios native application using Salesforce Mobile SDK
*     with app name:        SFNative
*          package name:    com.swyftmobile.forsf
*          organization:    Swyft Technology L.L.C.
*
*     in:                   SFNative
*
*     from template repo:   https://github.com/forcedotcom/SalesforceMobileSDK-Templates#v5.1.0
*          template path:   iOSNativeTemplate
*
********************************************************************************

/Users/davidfekke/Documents/xcode/SFNative /Users/davidfekke/Documents/xcode
Installing npm dependencies
npm notice created a lockfile as package-lock.json. You should commit this file.
up to date in 0.863s
Installing pod dependencies
Update all pods
Updating local specs repositories
  $ /usr/local/bin/git -C /Users/davidfekke/.cocoapods/repos/master fetch origin --progress
  remote: Counting objects: 9, done.
  remote: Compressing objects: 100% (8/8), done.
  remote: Total 9 (delta 6), reused 0 (delta 0), pack-reused 0
  From https://github.com/CocoaPods/Specs
     c25977ecedd..d4724ec3d69  master     -> origin/master
  $ /usr/local/bin/git -C /Users/davidfekke/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/local/bin/git -C /Users/davidfekke/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at d4724ec3d69 [Add] R.swift 3.3.0
Analyzing dependencies
Fetching podspec for `SalesforceAnalytics` from `node_modules/SalesforceMobileSDK-iOS`
[!] No podspec found for `SalesforceAnalytics` in `node_modules/SalesforceMobileSDK-iOS`

[!] Automatically assigning platform ios with version 9.0 on target SFNative because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
/Users/davidfekke/Documents/xcode
forceios failed

Command failed: pod update
`

**Comment by wmathurin** [comment]
There is a bug with npm 5 (see https://github.com/npm/npm/issues/16834).
Until it get resolved, we recommend you downgrade to npm 4.

**Comment by davidfekke** [comment]
Thanks.

**Comment by davidfekke** [comment]
@wmathurin, Should I also downgrade my Node to an earlier version? I downgraded NPM to version 4.6.1, but now I am getting the following error message from NPM;

```
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'realize-package-specifier'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/davidfekke/.npm/_logs/2017-05-31T20_29_48_086Z-debug.log
```

**Comment by wmathurin** [comment]
It's probably a good idea to do a clean re-install of node also.

**Comment by davidfekke** [comment]
I completely deleted NPM from my system. I did a clean reinstall, but using the LTS version of Node.js, specifically v6.10.3. After doing a reinstall, I was able to run `forceios create`, and it ran properly on my system. Thanks for your help.

**Comment by wmathurin** [comment]
FYI, in the next release (5.2), we changed the way we download the mobile sdk dependencies.
We use git directly instead of using npm. As a result it is faster and also npm 5 is okay.

**Comment by CesarRN** [comment]
Hi,

I have the same problem.

Today, I am trying to create a project with "forceios" and I understand that the tool is trying to use 5.2....

What´s the problem?

Thanks!

Pd: Error:

_forceios failed
Command failed: pod update_

**Comment by wmathurin** [comment]
Could you run with the `--verbose` flag and let us know what error are reported?
