### ISSUE TITLE
forceios create failed

### ISSUE THREAD

**Issue by mcekol** [forcedotcom/SalesforceMobileSDK-Package#59]
Hi all, while following the tutorial on 
https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/hybrid_ios.htm
I got the following issue. Please let me know if there is anything I'm doing wrong. 

➜  forceios version  
forceios version 5.3.0
➜   node --version     
v6.11.0
➜  npm --version     
3.10.10
➜  cordova --version
7.0.1

➜  forceios create
Enter your application type (native, native_swift, react_native, hybrid_local, hybrid_remote): hybrid_local
Enter your application name: externaltest
Enter the package name for your app (com.mycompany.myapp): com.external.test
Enter your organization name (Acme, Inc.): Acmee
Enter output directory for your app (leave empty for the current directory): 

********************************************************************************

   Creating ios hybrid_local application using Salesforce Mobile SDK
     with app name:        externaltest
          package name:    com.external.test
          organization:    Acmee
   
     in:                   externaltest
   
     from template repo:   https://github.com/forcedotcom/SalesforceMobileSDK-Templates#v5.0.1
          template path:   HybridLocalTemplate
          plugin repo:     https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v5.0.1

********************************************************************************

Creating a new cordova project.
/Users/xxxxx/Documents/GIT/test/sdk5test/externaltest /Users/xxxxx/Documents/GIT/test/sdk5test
com.external.test@1.0.0 /Users/xxxxx/Documents/GIT/test/sdk5test/externaltest
└─┬ shelljs@0.7.0 
  ├─┬ glob@7.1.2 
  │ ├── fs.realpath@1.0.0 
  │ ├─┬ inflight@1.0.6 
  │ │ └── wrappy@1.0.2 
  │ ├── inherits@2.0.3 
  │ ├─┬ minimatch@3.0.4 
  │ │ └─┬ brace-expansion@1.1.8 
  │ │   ├── balanced-match@1.0.0 
  │ │   └── concat-map@0.0.1 
  │ ├── once@1.4.0 
  │ └── path-is-absolute@1.0.1 
  ├── interpret@1.0.4 
  └─┬ rechoir@0.6.2 
    └─┬ resolve@1.4.0 
      └── path-parse@1.0.5 

/Users/xxxxx/Documents/GIT/test/sdk5test
/Users/xxxxx/Documents/GIT/test/sdk5test/externaltest /Users/xxxxx/Documents/GIT/test/sdk5test
Using cordova-fetch for cordova-ios@4.3.0
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.external.test
	Name: externaltest
iOS project created with cordova-ios@4.3.0
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
--save flag or autosave detected
Saving ios@~4.3.0 into config.xml file ...
/Users/xxxxx/Documents/GIT/test/sdk5test
/Users/xxxxx/Documents/GIT/test/sdk5test/externaltest /Users/xxxxx/Documents/GIT/test/sdk5test
/Users/xxxxx/Documents/GIT/test/sdk5test
forceios create failed

Command failed: cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v5.0.1 --force
Error: Failed to fetch plugin https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v5.0.1 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 235 Error output:
npm ERR! addLocal Could not install /var/folders/xp/x1zhh8k17rz8vmgpm4v5g32h0000gn/T/npm-15283-dfbcd71a/git-cache-4fa7f2ca/91694e74a284facec322125ccb7da4471d2c4d62
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/xxxxx/.nvm/versions/node/v6.11.0/bin/node" "/Users/xxxxx/.nvm/versions/node/v6.11.0/bin/npm" "install" "https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v5.0.1" "--save"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxxxx/Documents/GIT/test/sdk5test/externaltest/node_modules/npm-debug.log

**Comment by wmathurin** [comment]
From the output (looking at the URL of the template/plugin and the cordova ios version), it looks like you are actually running forceios 5.0.1.
May be you should npm uninstall and install forceios and make sure you are actually running forceios 5.3.0.
