### ISSUE TITLE
Cannot install forcedroid V 6.0.0, due to OS requirement

### ISSUE THREAD

**Issue by prab-git** [forcedotcom/SalesforceMobileSDK-Package#87]
forcedroid install using npm doesnt happen because of the OS requirement.

**Comment by prab-git** [comment]
[npm-debug.log](https://github.com/forcedotcom/SalesforceMobileSDK-Package/files/1585425/npm-debug.log)

**Comment by shrutibakshi** [comment]
I am facing the same issue for forcehybrid though I was able to install forcedroid on same environment without any issues. Pls could someone help with the resolution

**Comment by bhariharan** [comment]
We had restricted `forcehybrid` and `forcereact` to `Mac OS X`. We have removed that restriction [here](https://github.com/forcedotcom/SalesforceMobileSDK-Package/pull/89). On your existing installation of `forcehybrid` or `forcereact`, open up its `package.json` and remove the line `"os" : ["darwin"]`. If you've installed the package locally, you can find this file in `node_modules/forcehybrid/package.json`.

**Comment by shrutibakshi** [comment]
I am installing forcehybrid in a new environment using npm install on Windows. Still facing the same OS restriction error.

**Comment by bhariharan** [comment]
@shrutibakshi We have published a new version of `forcehybrid` that fixes this problem (`v6.0.1`). You can grab the latest [here](https://www.npmjs.com/package/forcehybrid).
