### ISSUE TITLE
Camera plugin in forcedroid

### ISSUE THREAD

**Issue by cloudterritory** [forcedotcom/SalesforceMobileSDK-Package#88]
I am working on a hybrid app which is based on forcedroid. but i'm not able to use latest cordova camera plugins (V2.4 or V3.0) in this. when i add plugin using CLI (cordova plugin add cordova-plugin-camera@2.4) and try to build a project using android studio , it is not working. after add this latest plugin in project it shows resources issues like (sf__icon, classes in hybridapp folder) are missing. however old camera plugin (V2.1) is working fine. but i want to use this latest plugin in my forcedroid app. If anyone faced this issue before and fixed, please tell me steps. also i want to know how to update android platform of forcedroid app.

**Comment by bhariharan** [comment]
Our `Android` plugin has a few postinstall steps that need to be run. This requires our plugin to be added at the end. If you use `forcedroid` to create your app, you need to remove our plugin, add the camera plugin and then re-add our plugin for the postinstall steps to kick in. The steps would look like this:
```
forcehybrid create ...
cd <app-folder>
cordova plugin remove com.salesforce
cordova plugin add <camera plugin>
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin --force
cordova prepare
Import into Android Studio
```

**Comment by cloudterritory** [comment]
@bhariharan, 
When i add forcehybrid using command(npm install forcehybrid).it shows compatibility issue in my windows laptop.
please take a look 
Unsupported platform for forcehybrid@6.0.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
![image](https://user-images.githubusercontent.com/33016927/34373141-6a872cb8-eaff-11e7-8c31-dd229ac0d338.png)

**Comment by bhariharan** [comment]
@cloudterritory We had an issue that restricted `forcehybrid` to only `Mac OS` machines. We have fixed that issue in our patch release - `v6.0.1`. Try again with `forcehybrid@6.0.1` from [here](https://www.npmjs.com/package/forcehybrid).

**Comment by cloudterritory** [comment]
@bhariharan, Thanks for help over platform and camera plugin issue. :)

**Comment by cloudterritory** [comment]
@bhariharan, We want to replace default login screen to our custom login screen. we got one solution, which is login through community url. where we can add our custom login page from server. but it allows only one salesforce org at time and we want to auth any org. so we want to design login screen in app. Is it possible in forcehybrid (Cordova Hybrid) app. [AuthTemplate](https://github.com/forcedotcom/SalesforceMobileSDK-AuthTemplates) is this link related to custom login screen in hybrid app? please provide any helpful or guidance on this.

**Comment by bhariharan** [comment]
@cloudterritory `AuthTemplates` are not custom login screen templates, they demonstrate usage of our new IDP auth feature in `6.0`. Our dev guide provides information on how to customize the login experience - see [here](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/auth_customize_login.htm?search_text=login%20screen).

**Comment by cloudterritory** [comment]
@bhariharan, Thank  for reply. we got this solution earlier but according to this doc if we use community url in app then it will allow one related org's users to login, not all. but we want our banding login screen for multiple salesforce orgs. so is it possible to develop a custom login screen for multiple orgs in salesforce SDK.

**Comment by bhariharan** [comment]
The login page itself is a server side component that we simply render within a `WebView` on mobile. Please review [Salesforce documentation](https://help.salesforce.com/home) for details on this.
