### ISSUE TITLE
forcereact create fails due to Cocoa Pods failing to install Boost 1.59.0

### ISSUE THREAD

**Issue by quantumninja** [forcedotcom/SalesforceMobileSDK-Package#97]
I've been trying to do the Trailhead React Native tutorial but am at this point not able to find a way to actually run `forcereact create` for ios without running into install issues with the boost library (1.59.0).

````
Installing boost (1.59.0)
[!] /usr/bin/tar xfz /Users/MYDIRECTORY/dev/sftestapp/ios/Pods/boost/file.tgz -C /Users/MYDIRECTORY/dev/sftestapp/ios/Pods/boost

tar: Unrecognized archive format
tar: Error exit delayed from previous errors.


[!] 'boost' uses the unencrypted http protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts in there. Please reach out to the library author to notify them of this security issue.
/Users/MYDIRECTORY/dev
forcereact failed
````
I think this might have been fixed with the latest RC but at this point I can't work out how to get this installer to actually work beyond this point. 

I've tried doing a default react-native init app and that works fine.

I've tried the quick fix solutions referenced at https://github.com/CocoaPods/cocoapods-downloader/issues/69 as well but can't get those to work with the forcereact CLI either.

**Comment by wmathurin** [comment]
Have you looked at the recommendation here: https://github.com/CocoaPods/CocoaPods/issues/7376

RN has a fix in 0.53 (see https://github.com/facebook/react-native/commit/cf19833). When we upgrade to 0.53 (in the next release #safeharbor), the issue should go away.

**Comment by quantumninja** [comment]
@wmathurin I didn't see that one but I also have't seen a git repo for this library at all that hasn't been forked for other purposes. When is the next release due out?

**Comment by wmathurin** [comment]
Early March #safeharbor

**Comment by wmathurin** [comment]
Mobile SDK 6.1 is now out and uses React Native 0.53.3. This issue should be resolved.
